# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib D3M
#' @importFrom Rcpp evalCpp
NULL

sort_rcpp <- function(x) {
    .Call('D3M_sort_rcpp', PACKAGE = 'D3M', x)
}

percentile_rcpp <- function(x, percentile) {
    .Call('D3M_percentile_rcpp', PACKAGE = 'D3M', x, percentile)
}

wasserCpp <- function(x, y, paranum = 101L, q = 2L) {
    .Call('D3M_wasserCpp', PACKAGE = 'D3M', x, y, paranum, q)
}

wasserCpp_mat <- function(xMat, yMat, paranum = 101L, q = 2L) {
    .Call('D3M_wasserCpp_mat', PACKAGE = 'D3M', xMat, yMat, paranum, q)
}

randomShuffle <- function(a) {
    .Call('D3M_randomShuffle', PACKAGE = 'D3M', a)
}

permCpp <- function(casesMat, controlMat, d, bsn = 10000L, qn = 101L, q = 2L) {
    .Call('D3M_permCpp', PACKAGE = 'D3M', casesMat, controlMat, d, bsn, qn, q)
}

